name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/Prasanth-Studio

            git pull origin main

            sudo docker stop prasanth-website || true
            sudo docker rm prasanth-website || true

            sudo docker build -t prasanth-studio .

            sudo docker run -d \
              --name prasanth-website \
              -p 80:80 \
              prasanth-studio